const planes = [
  {
    nombre: "KONAX Cobros",
    codigo: "cobros",
    precioMensual: "49",
    precioAnual: "499",
    color: "#2563eb",

    modulos: {
      clientes: true,
      vista_cliente: true,
      caja: true,
      control_caja: false,
      cobranza: true,
      inventario: false,
      venta_credito: true,
      suscripciones: false,
      recargos: false,
      dashboard_ventas: false,
      dashboard_cobros: true,
      dashboard_ejecutivo: false,
      egresos: false,
    },

    incluye: [
      "Clientes",
      "Vista Cliente",
      "Créditos",
      "Caja Básica",
      "Cobranza",
      "Gestión de Cobros",
      "Promesas de Pago",
      "Dashboard de Cobranza",
    ],
  },

  {
    nombre: "KONAX Ventas y Gestión",
    codigo: "gestion",
    precioMensual: "99",
    precioAnual: "999",
    color: "#10b981",

    modulos: {
      clientes: true,
      vista_cliente: true,
      caja: true,
      control_caja: true,
      cobranza: true,
      inventario: true,
      venta_credito: true,
      suscripciones: false,
      recargos: false,
      dashboard_ventas: true,
      dashboard_cobros: true,
      dashboard_ejecutivo: false,
      egresos: true,
    },

    incluye: [
      "Todo KONAX Cobros",
      "Inventario",
      "Venta Crédito",
      "Caja",
      "Control de Caja",
      "Gastos / Egresos",
      "Dashboard de Ventas",
      "Dashboard de Cobranza",
      "Reportes Operativos",
    ],
  },

  {
    nombre: "KONAX Pro",
    codigo: "pro",
    precioMensual: "149",
    precioAnual: "1499",
    color: "#111827",

    modulos: {
      clientes: true,
      vista_cliente: true,
      caja: true,
      control_caja: true,
      cobranza: true,
      inventario: true,
      venta_credito: true,
      suscripciones: true,
      recargos: true,
      dashboard_ventas: true,
      dashboard_cobros: true,
      dashboard_ejecutivo: true,
      egresos: true,
    },

    incluye: [
      "Todo KONAX Ventas y Gestión",
      "Suscripciones y Membresías",
      "Recargos Automáticos",
      "Dashboard Ejecutivo",
      "Dashboard de Ventas",
      "Dashboard de Cobranza",
      "Reportes Avanzados",
      "Indicadores Gerenciales",
      "Soporte Prioritario",
    ],
  },
];
